import Link from "next/link";
import { ArrowRight, BarChart3, Database, Eye, MoveUpRight, ShieldCheck, Target } from "lucide-react";
import { AppShell, SectionHeading, SourceBadge } from "../../components/app-shell";
import { stripeTestModeStatus } from "../../lib/server/stripe-service";

export const metadata = { title: "Bid the Moment · Boost exposure" };

export default function BoostPage() {
  const payment = stripeTestModeStatus();
  return <AppShell><div className="container page-hero">
    <div className="page-hero-grid"><div><div className="eyebrow">BID THE MOMENT · BOOSTED DISTRIBUTION</div><h1>Bid for the moment. Keep the rank honest.</h1><p>Bid the Moment is the paid distribution lane for reaching more of the right audience—not for moving an organic result. Every placement is labeled and every billable event is qualified.</p></div><div className="page-hero-aside"><span>campaign repository</span><strong>Production</strong><SourceBadge source="sponsored" compact /></div></div>
    <div className="section-tight"><div className="signal-principle" style={{ marginTop: 0 }}><div><div className="eyebrow">THE LINE IN THE SAND</div><h2>You cannot buy the rank. You can buy the spotlight.</h2></div><div className="signal-principle-copy"><p>Organic rank and boosted distribution are separate systems, separate metrics, and separate labels. Spend is never an input to Heat Score.</p><div className="principle-points"><div className="principle-point"><strong>Organic rank</strong><span>Verified attention signals only.</span></div><div className="principle-point"><strong>Sponsored reach</strong><span>Qualified impressions and clicks only.</span></div></div></div></div></div>
    <div className="section-tight"><SectionHeading title="How Bid the Moment works" description="A server-validated flow that keeps paid delivery inspectable." /><div className="category-grid"><div className="category-card"><div><Target size={20} color="#ef7359" /><h3>Select a placement</h3><p>Homepage, category, profile recommendation, or breakout feed.</p></div><div className="category-count"><span>01</span><ArrowRight size={16} /></div></div><div className="category-card"><div><Eye size={20} color="#ef7359" /><h3>Qualify delivery</h3><p>At least 50% visible for about one second, with duplicate and bot filtering.</p></div><div className="category-count"><span>02</span><ArrowRight size={16} /></div></div><div className="category-card"><div><BarChart3 size={20} color="#ef7359" /><h3>Report separately</h3><p>Impressions, clicks, CTR, and engaged visits never merge into organic traffic.</p></div><div className="category-count"><span>03</span><ArrowRight size={16} /></div></div></div></div>
    <div className="section-tight"><div className="panel"><div className="panel-heading"><div><h2>Production campaign ledger</h2><p>No sample campaigns are shown. Signed-in owners see only campaign rows persisted for their verified sites.</p></div><Database size={18} color="#2f8b62" /></div><div className="empty-state"><Database size={22} /><h3>Open your campaign workspace</h3><p>Create a persistent draft, reserve available inventory, and inspect recorded delivery from the owner dashboard.</p><Link className="button button-coral" href="/dashboard/boosts">Open Boost dashboard <MoveUpRight size={14} /></Link></div></div></div>
    <div className="section-tight"><div className="method-note"><ShieldCheck size={14} /> <strong>Payment gate:</strong> {payment.configured ? "Stripe credentials are present, but checkout remains subject to final verification." : "Stripe was skipped. Campaign drafts and inventory persist, but campaigns cannot become paid or active until signed payment confirmation is configured."}</div></div>
  </div></AppShell>;
}
