import Link from "next/link";
import { ArrowRight, BarChart3, BadgeCheck, ExternalLink, ShieldCheck, Target } from "lucide-react";
import { notFound } from "next/navigation";
import { AppShell, SourceBadge } from "../../../../components/app-shell";
import { DashboardShell, DashboardTopline, DemoNotice } from "../../../../components/dashboard-shell";
import { SiteMark } from "../../../../components/site-mark";
import { getSite } from "../../../../lib/demo-data";

export default async function SiteDashboardPage({ params }: { params: Promise<{ siteId: string }> }) {
  const { siteId } = await params;
  const site = getSite(siteId) ?? (await import("../../../../lib/demo-data")).DEMO_SITES.find((candidate) => candidate.siteId === siteId);
  if (!site) notFound();
  return <AppShell><DashboardShell active="/dashboard/sites"><DashboardTopline title={site.name} description={`${site.domain} · owner workspace`} action={<Link className="button button-quiet" href={`/go/${site.slug}`} prefetch={false} target="_blank" rel="noreferrer">Visit site <ExternalLink size={14} /></Link>} /><DemoNotice>Changes are simulated in this preview.</DemoNotice><div className="profile-title" style={{ margin: "23px 0" }}><SiteMark site={site} size="large" /><div><h2 style={{ margin: 0 }}>{site.name}</h2><p style={{ margin: 3, color: "var(--foreground-muted)" }}>Rank #{site.rank || "—"} · Heat {site.heatScore}</p></div><SourceBadge source={site.verification === "unverified" ? "unverified" : site.verification} /></div><div className="dashboard-grid"><div className="dashboard-card"><small>Visitors / 24H</small><strong>{site.visitors?.toLocaleString() ?? "—"}</strong><p>Demo source</p></div><div className="dashboard-card"><small>Online now</small><strong>{site.activeNow?.toLocaleString() ?? "—"}</strong><p>{site.activeNow === null ? "GA4 window" : "Tracker heartbeat"}</p></div><div className="dashboard-card"><small>Referrals</small><strong>{site.surgeReferrals.toLocaleString()}</strong><p>SurgeIndex direct</p></div><div className="dashboard-card"><small>Data sync</small><strong>3m</strong><p>Fresh · demo</p></div></div><div className="section-tight"><div className="category-grid"><Link className="category-card" href={`/dashboard/sites/${site.siteId}/analytics`}><div><BarChart3 size={19} color="#ef7359" /><h3>Analytics</h3><p>Traffic, rank history, and referral detail.</p></div><ArrowRight size={16} /></Link><Link className="category-card" href={`/dashboard/sites/${site.siteId}/verification`}><div><ShieldCheck size={19} color="#2f8b62" /><h3>Verification</h3><p>Tracker installation and GA4 connection architecture.</p></div><ArrowRight size={16} /></Link><Link className="category-card" href={`/dashboard/sites/${site.siteId}/badge`}><div><BadgeCheck size={19} color="#3977bd" /><h3>Badge</h3><p>Preview and copy a safe profile badge embed.</p></div><ArrowRight size={16} /></Link></div></div><div className="section-tight"><div className="panel"><div className="panel-heading"><div><h2>Promote without changing rank</h2><p>Start a separate sponsored campaign for {site.name}.</p></div><Target size={17} color="#bc7628" /></div><Link className="button button-coral" href="/dashboard/boosts">Create a demo boost <ArrowRight size={15} /></Link></div></div></DashboardShell></AppShell>;
}
