import Link from "next/link";
import { ArrowRight, BarChart3, BadgeCheck, ExternalLink, ShieldCheck, Target } from "lucide-react";
import { notFound } from "next/navigation";
import { AppShell, DataModeBadge, SourceBadge } from "../../../../components/app-shell";
import { DashboardShell, DashboardTopline, DemoNotice } from "../../../../components/dashboard-shell";
import { SiteMark } from "../../../../components/site-mark";
import { requirePageUser } from "../../../../lib/server/authorization";
import { getPublicDataProvider } from "../../../../lib/server/public-provider";

export default async function SiteDashboardPage({ params }: { params: Promise<{ siteId: string }> }) {
  const user = await requirePageUser();
  const { siteId } = await params;
  const provider = getPublicDataProvider();
  const site = await provider.getOwnedSite(user.id, siteId);
  if (!site) notFound();
  const isDemo = site.isDemo;
  return <AppShell><DashboardShell active="/dashboard/sites"><DashboardTopline title={site.name} description={`${site.domain} · owner workspace`} action={<Link className="button button-quiet" href={`/go/${site.slug}`} prefetch={false} target="_blank" rel="noreferrer">Visit site <ExternalLink size={14} /></Link>} />{isDemo ? <DemoNotice>Changes are simulated in this preview.</DemoNotice> : <div className="demo-ribbon dashboard-notice"><DataModeBadge isDemo={false} compact /> <span>Site state is read from the production repository.</span></div>}<div className="profile-title" style={{ margin: "23px 0" }}><SiteMark site={site} size="large" /><div><h2 style={{ margin: 0 }}>{site.name}</h2><p style={{ margin: 3, color: "var(--foreground-muted)" }}>Rank {site.rank ? `#${site.rank}` : "—"} · Heat {site.heatScore || "—"}</p></div><SourceBadge source={site.verification === "unverified" ? "unverified" : site.verification} /></div><div className="dashboard-grid"><div className="dashboard-card"><small>Visitors / 24H</small><strong>{site.visitors?.toLocaleString() ?? "—"}</strong><p>{site.visitors === null ? "No verified traffic yet" : "Persisted source signal"}</p></div><div className="dashboard-card"><small>Online now</small><strong>{site.activeNow?.toLocaleString() ?? "—"}</strong><p>{site.activeNow === null ? "Source not connected" : "Persisted heartbeat signal"}</p></div><div className="dashboard-card"><small>Referrals</small><strong>{site.surgeReferrals ? site.surgeReferrals.toLocaleString() : "—"}</strong><p>{site.surgeReferrals ? "Persisted SurgeIndex aggregate" : "No referral aggregate yet"}</p></div><div className="dashboard-card"><small>Data sync</small><strong>{isDemo ? "3m" : site.lastUpdatedAt ? "available" : "—"}</strong><p>{isDemo ? "Fresh · demo" : "Production freshness"}</p></div></div><div className="section-tight"><div className="category-grid"><Link className="category-card" href={`/dashboard/sites/${site.siteId}/analytics`}><div><BarChart3 size={19} color="#ef7359" /><h3>Analytics</h3><p>Traffic, rank history, and referral detail.</p></div><ArrowRight size={16} /></Link><Link className="category-card" href={`/dashboard/sites/${site.siteId}/verification`}><div><ShieldCheck size={19} color="#2f8b62" /><h3>Verification</h3><p>Review ownership and traffic-source status.</p></div><ArrowRight size={16} /></Link><Link className="category-card" href={`/dashboard/sites/${site.siteId}/badge`}><div><BadgeCheck size={19} color="#3977bd" /><h3>Badge</h3><p>Preview and copy a safe profile badge embed.</p></div><ArrowRight size={16} /></Link></div></div><div className="section-tight"><div className="panel"><div className="panel-heading"><div><h2>Promote without changing rank</h2><p>Paid distribution remains a separate product lane.</p></div><Target size={17} color="#bc7628" /></div><Link className="button button-coral" href="/dashboard/boosts">Review boost rules <ArrowRight size={15} /></Link></div></div></DashboardShell></AppShell>;
}
