import Link from "next/link";
import { connection } from "next/server";
import { ArrowRight, Filter, Sparkles } from "lucide-react";
import { AppShell, DataModeBadge, SectionHeading } from "../../components/app-shell";
import { CompactRankingRow } from "../../components/leaderboard-card";
import { getPublicDataProvider } from "../../lib/server/public-provider";

export const metadata = { title: "Live rankings" };

export default async function RankingsPage() {
  await connection();
  const provider = getPublicDataProvider();
  const [sites, categories] = await Promise.all([provider.getLeaderboard({ window: "live" }), provider.getCategories()]);
  return <AppShell><div className="container page-hero"><div className="page-hero-grid"><div><div className="eyebrow">THE ORGANIC BOARD</div><h1>Attention, in motion.</h1><p>See which websites are earning momentum from verified traffic, growth, and live activity. Paid boosts are always kept outside this board.</p></div><div className="page-hero-aside"><span>sites in index</span><strong>{sites.length}</strong><DataModeBadge isDemo={provider.source === "demo"} compact /></div></div><div className="section-tight"><SectionHeading title="Global leaderboard" description={provider.source === "demo" ? "Change the lens or explore a category. Every value below is simulated for this preview." : "Change the lens or explore a category. Only persisted production records appear here."} action={<Link className="button button-coral button-small" href="/submit">Submit a site <ArrowRight size={14} /></Link>} /><div className="window-tabs"><span className="window-tab window-tab-active">Live</span><Link className="window-tab" href="/?window=24h">24H</Link><Link className="window-tab" href="/?window=7d">7D</Link><Link className="window-tab" href="/breakouts">Breakout</Link><span className="window-tab">New</span></div><div className="category-scroll" style={{ marginTop: 14 }}><span className="category-pill category-pill-active"><Filter size={13} /> All</span>{categories.map((category) => <Link className="category-pill" key={category.slug} href={`/categories/${category.slug}`}>{category.name} · {category.siteCount}</Link>)}</div>{sites.length ? <div className="ranking-table"><div className="ranking-table-head"><span>Rank</span><span>Move</span><span>Website</span><span>Category</span><span>Heat</span><span>Visitors</span><span>Growth</span><span>Source</span><span>Trend</span><span /></div>{sites.map((site) => <CompactRankingRow key={site.siteId} site={site} />)}</div> : <div className="empty-state"><span className="empty-icon"><Filter size={18} /></span><h3>{provider.source === "demo" ? "No sites are in this preview view yet." : "The live rankings are waiting for their first sites."}</h3><p>{provider.source === "demo" ? "Try another ranking window or category, or submit a site to explore the workflow." : "No persisted production sites are available yet. Submit a site to start the board; verified traffic can be connected after review."}</p><Link className="button button-quiet" href="/submit">Submit a site</Link></div>}{provider.source === "demo" ? <div className="demo-ribbon"><Sparkles size={13} /> <DataModeBadge isDemo compact /> <span>Production mode replaces these fixtures with server-validated records.</span></div> : null}</div></div></AppShell>;
}
