import { AppShell } from "../../components/app-shell";

export const metadata = { title: "Acceptable Use" };

export default function AcceptableUsePage() {
  return <AppShell><div className="container page-hero"><div className="page-hero-grid"><div><div className="eyebrow">ACCEPTABLE USE</div><h1>Keep the signal honest.</h1><p>SurgeIndex is a public discovery and measurement service. These rules protect visitors, site owners, and the integrity of the organic board.</p></div></div><div className="section-tight"><div className="methodology-copy">
    <section className="methodology-block"><h2>Do not manipulate measurement</h2><p>Do not generate, purchase, replay, or coordinate artificial traffic, events, sessions, clicks, impressions, referrals, or engagement to change a site’s Heat Score, rank, breakout status, or reported performance. Do not install the tracker on a property you do not control or have permission to measure.</p></section>
    <section className="methodology-block"><h2>Do not misrepresent identity or ownership</h2><p>Use accurate domain, organization, and contact information. Do not impersonate another person or organization, submit a domain without a legitimate basis, make an ownership claim without proof, or present unverified traffic as verified traffic.</p></section>
    <section className="methodology-block"><h2>Respect people and systems</h2><p>Do not use SurgeIndex to harass, threaten, dox, discriminate against, or target people. Do not probe, scan, scrape at abusive rates, bypass access controls, upload malware, send unsolicited bulk messages, or interfere with the service, its providers, or another site.</p></section>
    <section className="methodology-block"><h2>Keep submissions lawful and clear</h2><p>Submitted sites, descriptions, creative, and links must be lawful, accurate, and appropriate for the audience. Do not submit content that is fraudulent, deceptive, infringing, malicious, or designed to evade moderation. SurgeIndex may decline, limit, suspend, or remove a listing when necessary to protect the service or its users.</p></section>
    <section className="methodology-block"><h2>Sponsored distribution remains separate</h2><p>Sponsored placements, when enabled in a future commercial release, must remain clearly labeled and must not be used to buy organic rank or imply an endorsement. Public Free has no active paid checkout or live Boost placement. Any future commercial release will have separate pricing, advertising, refund, and payment terms.</p></section>
    <section className="methodology-block"><h2>Report a concern</h2><p>If you believe a listing, tracker installation, measurement result, or account violates these rules, preserve the relevant URL and a short explanation and use the operator contact route published with the service. Requests involving personal data or deletion should identify the affected account or domain without including passwords, tokens, or unnecessary personal information.</p></section>
    <section className="methodology-block"><h2>Review status</h2><p>This page is product documentation for the Public Free MVP. The owner must approve the final service terms, privacy notice, acceptable-use rules, retention schedule, and regional notices before public launch; this page is not legal advice.</p></section>
  </div></div></div></AppShell>;
}
