import Link from "next/link";
import { ArrowLeft, BarChart3, Sparkles } from "lucide-react";
import { notFound } from "next/navigation";
import { AppShell, SourceBadge } from "../../../../../components/app-shell";
import { DashboardShell, DashboardTopline, DemoNotice } from "../../../../../components/dashboard-shell";
import { getRankHistory, getSite, getTimeseries } from "../../../../../lib/demo-data";

export default async function AnalyticsPage({ params }: { params: Promise<{ siteId: string }> }) {
  const { siteId } = await params;
  const site = getSite(siteId) ?? (await import("../../../../../lib/demo-data")).DEMO_SITES.find((candidate) => candidate.siteId === siteId);
  if (!site) notFound();
  const history = getRankHistory(site.slug);
  const series = getTimeseries(site.slug, "referrals");
  return <AppShell><DashboardShell active="/dashboard/sites"><DashboardTopline title="Analytics" description={`${site.name} · performance and referral reporting`} action={<Link className="text-link" href={`/dashboard/sites/${site.siteId}`}><ArrowLeft size={14} /> Site overview</Link>} /><DemoNotice>Demo metrics are clearly labeled and do not represent production traffic.</DemoNotice><div className="section-tight"><div className="dashboard-grid"><div className="dashboard-card"><small>Visitors / 24H</small><strong>{site.visitors?.toLocaleString() ?? "—"}</strong><p>Tracker / GA4 source</p></div><div className="dashboard-card"><small>Growth</small><strong>{site.growthPct === null ? "—" : `${site.growthPct}%`}</strong><p>Against own baseline</p></div><div className="dashboard-card"><small>Referrals</small><strong>{site.surgeReferrals.toLocaleString()}</strong><p>Direct from SurgeIndex</p></div><div className="dashboard-card"><small>Engagement</small><strong>{site.engagementRate === null ? "—" : `${Math.round(site.engagementRate * 100)}%`}</strong><p>Demo source</p></div></div></div><div className="section-tight"><div className="profile-columns"><div className="panel chart-panel"><div className="panel-heading"><div><h2>Referral trend</h2><p>Outbound clicks from SurgeIndex, kept apart from site traffic.</p></div><SourceBadge source="surgeindex" compact /></div><div className="line-chart" style={{ display: "flex", alignItems: "end", gap: 8, padding: "15px 2px 0", borderBottom: "1px solid var(--border)" }}>{series.map((point) => <span key={point.t} title={`${point.t}: ${point.value}`} style={{ flex: 1, height: `${Math.max(7, (point.value / Math.max(...series.map((item) => item.value), 1)) * 100)}%`, borderRadius: "6px 6px 0 0", background: "var(--accent-soft)", borderTop: "2px solid var(--accent)" }} />)}</div><div className="chart-labels"><span>12 points</span><span>now</span></div></div><div className="panel"><div className="panel-heading"><div><h2>Rank history</h2><p>Organic snapshots · paid spend excluded.</p></div><BarChart3 size={16} color="#ef7359" /></div><div className="dashboard-list">{history.map((item) => <div className="dashboard-list-row" key={item.period}><div><strong>{item.period}</strong><span>Heat {item.heat}</span></div><strong>#{item.rank}</strong></div>)}</div></div></div></div><div className="section-tight"><div className="method-note"><Sparkles size={13} /> An engaged visit is only shown when the connected data source supports that definition. GA4 realtime active users are not relabeled as exact tracker online users.</div></div></DashboardShell></AppShell>;
}
