import Link from "next/link";
import { Check, Code2, FileKey2, Globe2, Info, ShieldCheck } from "lucide-react";
import { notFound } from "next/navigation";
import { AppShell, Breadcrumbs, SourceBadge } from "../../../components/app-shell";
import { DEMO_SITES, getSite } from "../../../lib/demo-data";

export default async function ClaimPage({ params }: { params: Promise<{ siteId: string }> }) {
  const { siteId } = await params;
  const site = getSite(siteId) ?? DEMO_SITES.find((candidate) => candidate.siteId === siteId);
  if (!site) notFound();
  const methods = [["meta_tag", "Meta tag", "Add a verification tag to your homepage.", Code2], ["html_file", "HTML file", "Upload a small file to the site root.", FileKey2], ["dns_txt", "DNS TXT", "Add a token to the domain DNS record.", Globe2], ["tracker", "SurgeIndex tracker", "Connect the traffic script and verify in one step.", ShieldCheck]] as const;
  return <AppShell><div className="container page-hero"><Breadcrumbs items={[{ label: "Live", href: "/" }, { label: site.name, href: `/site/${site.slug}` }, { label: "Claim" }]} /><div className="page-hero-grid"><div><div className="eyebrow">OWNERSHIP VERIFICATION</div><h1>Claim {site.name}.</h1><p>Ownership lets you update the listing and connect a data source. It does not automatically make traffic verified.</p></div><div className="page-hero-aside"><span>current listing status</span><strong>Unclaimed</strong><SourceBadge source={site.verification === "unverified" ? "unverified" : site.verification} compact /></div></div><div className="section-tight"><div className="profile-columns"><div className="panel"><div className="panel-heading"><div><h2>Choose a verification method</h2><p>Pick the one that matches how you can access {site.domain}.</p></div><Info size={16} color="#847b75" /></div><div className="dashboard-list">{methods.map(([id, name, description, Icon]) => <button className="dashboard-list-row claim-method" key={id}><div><strong>{name}</strong><span>{description}</span></div><Icon size={18} color="#ef7359" /></button>)}</div></div><div className="panel"><div className="panel-heading"><div><h2>What changes after claiming?</h2><p>Clear boundaries keep the directory credible.</p></div></div><div className="dashboard-list"><div className="dashboard-list-row"><div><strong>Listing edits</strong><span>Title, description, category, tags</span></div><Check size={17} color="#2f8b62" /></div><div className="dashboard-list-row"><div><strong>Traffic connection</strong><span>Separate step after ownership</span></div><Check size={17} color="#2f8b62" /></div><div className="dashboard-list-row"><div><strong>Organic rank</strong><span>Never purchasable, never guaranteed</span></div><ShieldCheck size={17} color="#2f8b62" /></div></div><Link className="button button-dark" style={{ marginTop: 22 }} href="/auth/sign-in">Sign in to continue</Link></div></div></div><div className="method-note"><Info size={14} /> Demo mode shows the verification architecture without mutating a real domain. Production will validate the proof server-side and record the method in the claim ledger.</div></div></AppShell>;
}
