import Link from "next/link";
import { ArrowRight, Check, Sparkles } from "lucide-react";
import { AppShell, SectionHeading, SourceBadge } from "../../components/app-shell";
import { demoPricing } from "../../lib/demo-data";

export const metadata = { title: "Pricing" };

export default function PricingPage() {
  return <AppShell><div className="container page-hero"><div className="page-hero-grid"><div><div className="eyebrow">SIMPLE WAYS TO SHOW UP</div><h1>Free to be found. Clear when you pay.</h1><p>Listing and organic ranking stay open. Boost packages buy transparent distribution, with sample delivery in demo mode until billing is connected.</p></div><div className="page-hero-aside"><span>pricing status</span><strong>Sample</strong><SourceBadge source="demo" compact /></div></div><div className="section-tight"><SectionHeading title="Boost packages" description="These demo packages are configuration-driven examples, not live offers. Stripe activates production campaigns only after a signed webhook confirms payment." /><div className="pricing-grid">{demoPricing.map((plan) => <article className={`price-card ${plan.popular ? "price-card-popular" : ""}`} key={plan.name}><h2>{plan.name}</h2><p>{plan.detail} for clearly labeled exposure.</p><div className="price">{plan.price}<small> / campaign</small></div><ul className="price-list"><li><Check size={15} /> {plan.impressions} target impressions</li><li><Check size={15} /> Organic rank stays unchanged</li><li><Check size={15} /> Valid clicks and CTR reporting</li><li><Check size={15} /> Category or homepage placement</li></ul><Link className={`button ${plan.popular ? "button-coral" : "button-quiet"}`} href="/boost">Review a demo boost <ArrowRight size={15} /></Link></article>)}</div><p className="pricing-note"><Sparkles size={13} /> Production pricing, taxes, currency, and availability require Stripe configuration and business review.</p></div><div className="section-tight"><div className="signal-principle"><div><div className="eyebrow">FREE, ALWAYS</div><h2>Organic visibility is not a paid tier.</h2></div><div className="signal-principle-copy"><p>Submit a site, connect a source, and let its attention signals do the work. Pro features such as longer history and alerts are waitlist-ready, but not represented as live in V1.</p><Link className="button button-coral" href="/submit">List your site <ArrowRight size={15} /></Link></div></div></div></div></AppShell>;
}
