CREATE TYPE "public"."breakout_state" AS ENUM('none', 'watch', 'breaking_out', 'surging', 'cooling', 'resolved', 'invalidated');--> statement-breakpoint
CREATE TYPE "public"."breakout_strength" AS ENUM('moderate', 'strong', 'exceptional');--> statement-breakpoint
CREATE TYPE "public"."freshness_state" AS ENUM('live', 'fresh', 'delayed', 'stale', 'offline');--> statement-breakpoint
CREATE TYPE "public"."ranking_state" AS ENUM('unverified', 'building_baseline', 'provisional', 'eligible', 'stale', 'suspended', 'fraud_review', 'ineligible');--> statement-breakpoint
CREATE TYPE "public"."scoring_job_status" AS ENUM('running', 'completed', 'failed');--> statement-breakpoint
ALTER TYPE "public"."activity_type" ADD VALUE 'breakout_entered';--> statement-breakpoint
ALTER TYPE "public"."activity_type" ADD VALUE 'breakout_cooling';--> statement-breakpoint
ALTER TYPE "public"."activity_type" ADD VALUE 'breakout_resolved';--> statement-breakpoint
ALTER TYPE "public"."activity_type" ADD VALUE 'league_changed';--> statement-breakpoint
ALTER TYPE "public"."activity_type" ADD VALUE 'score_recomputed';--> statement-breakpoint
CREATE TABLE "baseline_bucket" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "baseline_bucket_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"site_id" uuid NOT NULL,
	"bucket_start" timestamp with time zone NOT NULL,
	"visitors" integer DEFAULT 0 NOT NULL,
	"sessions" integer DEFAULT 0 NOT NULL,
	"pageviews" integer DEFAULT 0 NOT NULL,
	"engaged_sessions" integer DEFAULT 0 NOT NULL,
	"active_now" integer DEFAULT 0 NOT NULL,
	"valid_events" integer DEFAULT 0 NOT NULL,
	"data_completeness" numeric(5, 4) DEFAULT '1' NOT NULL,
	"source" text DEFAULT 'tracker' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "baseline_bucket_site_time_unique" UNIQUE("site_id","bucket_start")
);
--> statement-breakpoint
CREATE TABLE "breakout_event" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"site_id" uuid NOT NULL,
	"state" "breakout_state" DEFAULT 'none' NOT NULL,
	"strength" "breakout_strength",
	"rule_version" text NOT NULL,
	"detected_at" timestamp with time zone,
	"active_since" timestamp with time zone,
	"last_evaluated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"resolved_at" timestamp with time zone,
	"cooldown_until" timestamp with time zone,
	"duration_seconds" integer DEFAULT 0 NOT NULL,
	"baseline_visitors" bigint,
	"current_visitors" bigint,
	"absolute_lift" bigint,
	"relative_lift" numeric(10, 4),
	"live_ratio" numeric(10, 4),
	"confidence" numeric(5, 4) DEFAULT '0' NOT NULL,
	"explanation" text DEFAULT '' NOT NULL,
	"reason_codes" jsonb NOT NULL,
	"peak_metrics" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "breakout_state_transition" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"breakout_event_id" uuid NOT NULL,
	"from_state" "breakout_state",
	"to_state" "breakout_state" NOT NULL,
	"reason" text DEFAULT '' NOT NULL,
	"metrics" jsonb,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "current_ranking" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"site_id" uuid NOT NULL,
	"scope" text NOT NULL,
	"window" "rank_window" DEFAULT 'live' NOT NULL,
	"rank" integer NOT NULL,
	"previous_rank" integer,
	"score_id" uuid,
	"score_version" text NOT NULL,
	"displayed_score" integer NOT NULL,
	"smoothed_score" numeric(6, 3) NOT NULL,
	"ranking_state" "ranking_state" NOT NULL,
	"league" text NOT NULL,
	"generated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "current_ranking_site_scope_unique" UNIQUE("site_id","scope","window")
);
--> statement-breakpoint
CREATE TABLE "scoring_config" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"version" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"weights" jsonb NOT NULL,
	"baseline_config" jsonb NOT NULL,
	"eligibility_config" jsonb NOT NULL,
	"league_config" jsonb NOT NULL,
	"smoothing_config" jsonb NOT NULL,
	"breakout_config" jsonb NOT NULL,
	"released_at" timestamp with time zone DEFAULT now() NOT NULL,
	"is_active" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "scoring_config_version_unique" UNIQUE("version")
);
--> statement-breakpoint
CREATE TABLE "scoring_job_run" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"job_type" text NOT NULL,
	"version" text NOT NULL,
	"run_key" text NOT NULL,
	"status" "scoring_job_status" DEFAULT 'running' NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finished_at" timestamp with time zone,
	"duration_ms" integer,
	"sites_attempted" integer DEFAULT 0 NOT NULL,
	"sites_completed" integer DEFAULT 0 NOT NULL,
	"sites_skipped" integer DEFAULT 0 NOT NULL,
	"sites_failed" integer DEFAULT 0 NOT NULL,
	"cursor" text,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "scoring_job_run_key_unique" UNIQUE("job_type","version","run_key")
);
--> statement-breakpoint
CREATE TABLE "site_baseline" (
	"site_id" uuid PRIMARY KEY NOT NULL,
	"version" text NOT NULL,
	"method" text NOT NULL,
	"status" text DEFAULT 'building_baseline' NOT NULL,
	"expected_visitors" bigint,
	"lower_bound" bigint,
	"upper_bound" bigint,
	"typical_active_now" integer,
	"sample_count" integer DEFAULT 0 NOT NULL,
	"lookback_days" integer DEFAULT 0 NOT NULL,
	"confidence" numeric(5, 4) DEFAULT '0' NOT NULL,
	"data_completeness" numeric(5, 4) DEFAULT '0' NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "site_score" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"site_id" uuid NOT NULL,
	"score_version" text NOT NULL,
	"calculation_window" text DEFAULT 'live' NOT NULL,
	"calculation_slot" timestamp with time zone NOT NULL,
	"input_window_start" timestamp with time zone,
	"input_window_end" timestamp with time zone,
	"ranking_state" "ranking_state" NOT NULL,
	"freshness" "freshness_state" NOT NULL,
	"league" text NOT NULL,
	"raw_score" numeric(6, 3) NOT NULL,
	"smoothed_score" numeric(6, 3) NOT NULL,
	"displayed_score" integer NOT NULL,
	"confidence" numeric(5, 4) NOT NULL,
	"relative_lift" numeric(10, 4),
	"absolute_lift" bigint,
	"penalties" jsonb NOT NULL,
	"reason_codes" jsonb NOT NULL,
	"baseline_site_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "site_score_slot_unique" UNIQUE("site_id","score_version","calculation_window","calculation_slot")
);
--> statement-breakpoint
CREATE TABLE "site_score_component" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"score_id" uuid NOT NULL,
	"component" text NOT NULL,
	"normalized_value" numeric(6, 3) NOT NULL,
	"weight" numeric(5, 4) NOT NULL,
	"contribution" numeric(6, 3) NOT NULL,
	"available" boolean DEFAULT true NOT NULL,
	"detail" text DEFAULT '' NOT NULL,
	"input_values" jsonb,
	CONSTRAINT "site_score_component_unique" UNIQUE("score_id","component")
);
--> statement-breakpoint
ALTER TABLE "rank_snapshot" ADD COLUMN "score_version" text DEFAULT 'heat-v1' NOT NULL;--> statement-breakpoint
ALTER TABLE "rank_snapshot" ADD COLUMN "displayed_score" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "rank_snapshot" ADD COLUMN "smoothed_score" numeric(6, 3) DEFAULT '0' NOT NULL;--> statement-breakpoint
ALTER TABLE "rank_snapshot" ADD COLUMN "ranking_state" "ranking_state" DEFAULT 'eligible' NOT NULL;--> statement-breakpoint
ALTER TABLE "rank_snapshot" ADD COLUMN "league" text DEFAULT 'new' NOT NULL;--> statement-breakpoint
ALTER TABLE "site_metric_current" ADD COLUMN "ranking_state" "ranking_state" DEFAULT 'unverified' NOT NULL;--> statement-breakpoint
ALTER TABLE "site_metric_current" ADD COLUMN "freshness" "freshness_state" DEFAULT 'offline' NOT NULL;--> statement-breakpoint
ALTER TABLE "site_metric_current" ADD COLUMN "data_confidence" numeric(5, 4) DEFAULT '0' NOT NULL;--> statement-breakpoint
ALTER TABLE "site_metric_current" ADD COLUMN "last_baseline_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "site_metric_current" ADD COLUMN "last_score_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "site_metric_current" ADD COLUMN "breakout_state" "breakout_state" DEFAULT 'none' NOT NULL;--> statement-breakpoint
ALTER TABLE "site_metric_current" ADD COLUMN "breakout_strength" "breakout_strength";--> statement-breakpoint
ALTER TABLE "site_metric_snapshot" ADD COLUMN "valid_events" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "site_metric_snapshot" ADD COLUMN "data_completeness" numeric(5, 4) DEFAULT '0' NOT NULL;--> statement-breakpoint
ALTER TABLE "baseline_bucket" ADD CONSTRAINT "baseline_bucket_site_id_site_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."site"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "breakout_event" ADD CONSTRAINT "breakout_event_site_id_site_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."site"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "breakout_state_transition" ADD CONSTRAINT "breakout_state_transition_breakout_event_id_breakout_event_id_fk" FOREIGN KEY ("breakout_event_id") REFERENCES "public"."breakout_event"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "current_ranking" ADD CONSTRAINT "current_ranking_site_id_site_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."site"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "current_ranking" ADD CONSTRAINT "current_ranking_score_id_site_score_id_fk" FOREIGN KEY ("score_id") REFERENCES "public"."site_score"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "site_baseline" ADD CONSTRAINT "site_baseline_site_id_site_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."site"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "site_score" ADD CONSTRAINT "site_score_site_id_site_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."site"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "site_score" ADD CONSTRAINT "site_score_baseline_site_id_site_baseline_site_id_fk" FOREIGN KEY ("baseline_site_id") REFERENCES "public"."site_baseline"("site_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "site_score_component" ADD CONSTRAINT "site_score_component_score_id_site_score_id_fk" FOREIGN KEY ("score_id") REFERENCES "public"."site_score"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "baseline_bucket_site_time_idx" ON "baseline_bucket" USING btree ("site_id","bucket_start");--> statement-breakpoint
CREATE INDEX "breakout_site_state_idx" ON "breakout_event" USING btree ("site_id","state","last_evaluated_at");--> statement-breakpoint
CREATE INDEX "breakout_public_idx" ON "breakout_event" USING btree ("state","strength","detected_at");--> statement-breakpoint
CREATE INDEX "breakout_transition_event_time_idx" ON "breakout_state_transition" USING btree ("breakout_event_id","occurred_at");--> statement-breakpoint
CREATE INDEX "current_ranking_scope_rank_idx" ON "current_ranking" USING btree ("scope","window","rank");--> statement-breakpoint
CREATE INDEX "scoring_config_active_idx" ON "scoring_config" USING btree ("is_active","released_at");--> statement-breakpoint
CREATE INDEX "scoring_job_run_status_idx" ON "scoring_job_run" USING btree ("job_type","status","started_at");--> statement-breakpoint
CREATE INDEX "site_baseline_status_idx" ON "site_baseline" USING btree ("status","updated_at");--> statement-breakpoint
CREATE INDEX "site_score_site_time_idx" ON "site_score" USING btree ("site_id","created_at");--> statement-breakpoint
CREATE INDEX "site_score_state_idx" ON "site_score" USING btree ("ranking_state","league","displayed_score");--> statement-breakpoint
CREATE INDEX "site_score_component_score_idx" ON "site_score_component" USING btree ("score_id");