import Link from "next/link";
import { ArrowLeft, Check, FileCheck2, LockKeyhole, ShieldCheck } from "lucide-react";
import { AppShell } from "../../components/app-shell";
import { SubmitForm } from "../../components/submit-form";

export const metadata = { title: "Submit a website" };

export default function SubmitPage() {
  return <AppShell><div className="container page-hero"><Link className="text-link" href="/"><ArrowLeft size={14} /> Back to live board</Link><div className="page-hero-grid" style={{ marginTop: 26 }}><div><div className="eyebrow">A CLEAN START</div><h1>List the thing you’re building.</h1><p>SurgeIndex is open to public websites with something useful to show. Listing is free; verification is how a site turns traffic into evidence.</p></div><div className="page-hero-aside"><span>review time</span><strong>~2 min</strong><span>Demo review is immediate. Production review is moderated.</span></div></div><div className="section-tight"><SubmitForm /><div className="principle-points" style={{ marginTop: 16 }}><div className="principle-point" style={{ background: "var(--surface)", color: "var(--foreground)", borderColor: "var(--border)" }}><strong><FileCheck2 size={17} /> 1 · Review metadata</strong><span>We normalize the domain and let you edit the imported title, description, and category.</span></div><div className="principle-point" style={{ background: "var(--surface)", color: "var(--foreground)", borderColor: "var(--border)" }}><strong><ShieldCheck size={17} /> 2 · Verify ownership</strong><span>Use a meta tag, file, DNS TXT, tracker, or GA4. Ownership and traffic verification are separate.</span></div><div className="principle-point" style={{ background: "var(--surface)", color: "var(--foreground)", borderColor: "var(--border)" }}><strong><LockKeyhole size={17} /> 3 · Keep control</strong><span>Production integrations keep tokens server-side and never collect form contents through the tracker.</span></div></div></div><div className="method-note"><Check size={14} /> Public listing can happen before ownership verification, but it will remain marked <strong>Unclaimed</strong> and any traffic metrics remain <strong>Unverified</strong> until connected.</div></div></AppShell>;
}
