import Link from "next/link";
import { ArrowLeft, Check, FileCheck2, LockKeyhole, ShieldCheck } from "lucide-react";
import { AppShell } from "../../components/app-shell";
import { getServerEnv } from "@surge/config";
import { SubmitForm } from "../../components/submit-form";
import { ResendVerificationForm } from "../../components/password-recovery-form";
import { requirePageUser } from "../../lib/server/authorization";

export const metadata = { title: "Submit a website" };

export default async function SubmitPage() {
  const user = await requirePageUser("/submit", "sign-up");
  const env = getServerEnv();
  return <AppShell><div className="container page-hero submit-page"><Link className="text-link" href="/"><ArrowLeft size={14} /> Back to live board</Link><div className="page-hero-grid submit-page-hero" style={{ marginTop: 26 }}><div><div className="eyebrow">A CLEAN START</div><h1>List the thing you’re building.</h1><p>SurgeIndex is open to public websites with something useful to show. Listing is free; verification is how a site turns traffic into evidence.</p></div><div className="page-hero-aside"><span>submission time</span><strong>~2 min</strong><span>Production review is manual moderation; two minutes is the submission estimate, not a promise of approval.</span></div></div>{!user.emailVerified ? <div className="section-tight"><div className="panel verification-required" role="status"><div className="panel-heading"><div><div className="eyebrow">ACCOUNT CHECK</div><h2>Verify your email before submitting.</h2><p>We keep the submission queue tied to a verified account. Check your inbox, then return here to continue.</p></div><ShieldCheck size={18} color="#2f8b62" /></div><ResendVerificationForm turnstileSiteKey={env.TURNSTILE_SITE_KEY} initialEmail={user.email} /></div></div> : <div className="section-tight"><div className="submit-progress" aria-label="Submission progress"><span className="submit-progress-active"><Check size={14} /> Account verified</span><span><FileCheck2 size={14} /> Submit</span><span><ShieldCheck size={14} /> Review</span><span><LockKeyhole size={14} /> Claim</span><span><Check size={14} /> Connect tracker</span></div><SubmitForm turnstileSiteKey={env.TURNSTILE_SITE_KEY} /><div className="principle-points" style={{ marginTop: 16 }}><div className="principle-point principle-point-light" style={{ background: "var(--surface)", color: "var(--foreground)", borderColor: "var(--border)" }}><strong><FileCheck2 size={17} /> 1 · Review metadata</strong><span>We normalize the domain and let you edit the imported title, description, and category.</span></div><div className="principle-point principle-point-light" style={{ background: "var(--surface)", color: "var(--foreground)", borderColor: "var(--border)" }}><strong><ShieldCheck size={17} /> 2 · Verify ownership</strong><span>Use a meta tag or DNS TXT. Tracker and GA4 are separate traffic-source integrations, not ownership proof.</span></div><div className="principle-point principle-point-light" style={{ background: "var(--surface)", color: "var(--foreground)", borderColor: "var(--border)" }}><strong><LockKeyhole size={17} /> 3 · Keep control</strong><span>Production integrations keep tokens server-side and never collect form contents through the tracker.</span></div></div></div>}<div className="method-note"><Check size={14} /> Public listing can happen before ownership verification, but it will remain marked <strong>Unclaimed</strong> and any traffic metrics remain <strong>Unverified</strong> until connected.</div></div></AppShell>;
}
