import Link from "next/link";
import { and, desc, eq } from "drizzle-orm";
import { CreditCard, FileText, ShieldCheck } from "lucide-react";
import { getServerEnv } from "@surge/config";
import { boostCampaign, boostOrder, boostRefund, getPostgresDb } from "@surge/db";
import { AppShell } from "../../../components/app-shell";
import { DashboardShell, DashboardTopline, DemoNotice } from "../../../components/dashboard-shell";
import { requirePageUser } from "../../../lib/server/authorization";

export const metadata = { title: "Billing" };

function dateLabel(value: Date | null): string {
  return value ? value.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" }) : "Not paid";
}

export default async function BillingPage() {
  const user = await requirePageUser();
  const env = getServerEnv();
  if (!env.NEXT_PUBLIC_COMMERCIAL_ENABLED) {
    return <AppShell><DashboardShell><DashboardTopline title="Billing" description="Commercial billing is not part of the Public Free launch." /><div className="section-tight"><div className="empty-state"><ShieldCheck size={22} /><h3>Billing is closed</h3><p>Stripe, paid Boost, receipts, and payment actions remain unavailable until a separate Commercial release passes provider and legal review.</p><Link className="button button-quiet" href="/dashboard">Back to dashboard</Link></div></div></DashboardShell></AppShell>;
  }
  if (env.APP_MODE !== "production" || env.DATA_PROVIDER !== "postgres") {
    return <AppShell><DashboardShell active="/dashboard/billing"><DashboardTopline title="Billing" description="Payment architecture is present, with mock receipts in demo mode." action={<Link className="button button-quiet" href="/pricing">View pricing</Link>} /><DemoNotice>Nothing is charged in this preview.</DemoNotice><div className="section-tight"><div className="profile-columns"><div className="panel"><div className="panel-heading"><div><h2>Payment method</h2><p>Stripe Checkout is the production adapter.</p></div><CreditCard size={18} color="#3977bd" /></div><div className="dashboard-alert"><ShieldCheck size={16} /><span>No payment method is stored in demo mode. Production secrets remain server-side.</span></div></div><div className="panel"><div className="panel-heading"><div><h2>Receipts</h2><p>Demo payment records.</p></div><FileText size={17} /></div><div className="dashboard-list"><div className="dashboard-list-row"><div><strong>PixelForge boost</strong><span>Mock receipt · #demo_8J2D</span></div><span className="status-chip status-active">succeeded</span></div><div className="dashboard-list-row"><div><strong>ShopSignal boost</strong><span>Awaiting scheduled activation</span></div><span className="status-chip status-scheduled">pending</span></div></div></div></div></div></DashboardShell></AppShell>;
  }

  const db = getPostgresDb();
  const orders = await db.select({ id: boostOrder.id, campaignId: boostOrder.campaignId, packageKey: boostOrder.packageKey, currency: boostOrder.currency, expectedAmountCents: boostOrder.expectedAmountCents, paidAmountCents: boostOrder.paidAmountCents, refundedAmountCents: boostOrder.refundedAmountCents, stripeEnvironment: boostOrder.stripeEnvironment, paymentStatus: boostOrder.paymentStatus, paidAt: boostOrder.paidAt, createdAt: boostOrder.createdAt, headline: boostCampaign.headline }).from(boostOrder).innerJoin(boostCampaign, eq(boostCampaign.id, boostOrder.campaignId)).where(eq(boostOrder.userId, user.id)).orderBy(desc(boostOrder.createdAt));
  const refunds = await db.select({ id: boostRefund.id, orderId: boostRefund.orderId, amountCents: boostRefund.amountCents, status: boostRefund.status, reason: boostRefund.reason, createdAt: boostRefund.createdAt, currency: boostOrder.currency }).from(boostRefund).innerJoin(boostOrder, and(eq(boostOrder.id, boostRefund.orderId), eq(boostOrder.userId, user.id))).orderBy(desc(boostRefund.createdAt));

  return <AppShell><DashboardShell active="/dashboard/billing"><DashboardTopline title="Billing" description="Server-confirmed Boost orders, payment states, and refunds. Card details are never stored here." action={<Link className="button button-quiet" href="/pricing">View pricing</Link>} /><div className="demo-ribbon dashboard-notice"><CreditCard size={13} /> Stripe payment records are scoped to your account and retain their test/live environment.</div><div className="section-tight"><div className="panel"><div className="panel-heading"><div><h2>Orders and payments</h2><p>Amount and status come from the internal ledger; activation requires a verified webhook.</p></div><FileText size={17} /></div>{orders.length ? <div className="dashboard-list">{orders.map((order) => <div className="dashboard-list-row" key={order.id}><div><strong>{order.headline || "Boost campaign"}</strong><span>Order {order.id.slice(0, 8)} · {order.packageKey} · {order.stripeEnvironment} · created {dateLabel(order.createdAt)}</span></div><div style={{ textAlign: "right" }}><strong>{new Intl.NumberFormat("en-US", { style: "currency", currency: order.currency }).format(order.paidAmountCents / 100)}</strong><span className={`status-chip status-${order.paymentStatus === "succeeded" ? "active" : "scheduled"}`}>{order.paymentStatus} · expected {new Intl.NumberFormat("en-US", { style: "currency", currency: order.currency }).format(order.expectedAmountCents / 100)}</span><small>{order.paidAt ? `Paid ${dateLabel(order.paidAt)}` : "Not paid"} · refunded {new Intl.NumberFormat("en-US", { style: "currency", currency: order.currency }).format(order.refundedAmountCents / 100)}</small></div></div>)}</div> : <div className="empty-state"><FileText size={22} /><h3>No production orders</h3><p>Orders will appear after a server-created Stripe Checkout session is paid.</p></div>}</div></div><div className="section-tight"><div className="panel"><div className="panel-heading"><div><h2>Refunds</h2><p>Refund state follows Stripe confirmation and remains attached to campaign history.</p></div><ShieldCheck size={17} /></div>{refunds.length ? <div className="dashboard-list">{refunds.map((refund) => <div className="dashboard-list-row" key={refund.id}><div><strong>{new Intl.NumberFormat("en-US", { style: "currency", currency: refund.currency }).format(refund.amountCents / 100)}</strong><span>Order {refund.orderId.slice(0, 8)} · {refund.reason}</span></div><span className="status-chip status-scheduled">{refund.status}</span></div>)}</div> : <div className="empty-state"><h3>No refunds</h3><p>Authorized refund requests and Stripe confirmations will appear here.</p></div>}</div></div></DashboardShell></AppShell>;
}
